apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka-operator
spec:
  releaseName: strimzi-kafka-operator
  targetNamespace: kafka-operator
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.36.1
      sourceRef:
        kind: HelmRepository
        name: strimzi-helm
        namespace: helmrepos
  interval: 1m0s
  install:
    createNamespace: false

  values:
    watchNamespaces: ['kafka']